custom_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - id: step-caller
        uses: "./.github/actions/random_number"
        with:
          the-caller: 'Myself'
      - run: echo random-number ${{ steps.step-caller.outputs.random-number }}
        shell: bash

  build:
    if: "contains(github.event.head_commit.message, '[pipeline]')"
