name: devops-pipeline-F-R-M

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
      - name: testa ping
        run: ansible-playbook -vvvv ansible/ping.yml
