name: devops-pipeline-F-R-M

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step do job build
        run: echo Hello, world! Build.


  deploy:
    if: "contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-result
          path: build-result.txt
      - name: use of artifact created
        run: ls build-result.txt
